"""Paper writing stage — uses the *ml-paper-writing* skill."""

from __future__ import annotations

import re
import time
from pathlib import Path

from pipeline.base import BaseStage, StageResult, StageStatus
from pipeline.cache import CacheManager
from pipeline.config import ConfigLoader

_AUTO_GEN_START = "% AUTO-GENERATED"
_AUTO_GEN_END = "% END AUTO-GENERATED"


def _replace_autogenerated_blocks(tex_path: Path, new_content: str) -> None:
    """Replace every ``% AUTO-GENERATED … % END AUTO-GENERATED`` block in
    *tex_path* with *new_content*, leaving surrounding text intact.

    If no such block exists the file is left unchanged.
    """
    original = tex_path.read_text(encoding="utf-8")
    pattern = re.compile(
        rf"{re.escape(_AUTO_GEN_START)}.*?{re.escape(_AUTO_GEN_END)}",
        re.DOTALL,
    )
    if not pattern.search(original):
        return
    replacement = f"{_AUTO_GEN_START}\n{new_content}\n{_AUTO_GEN_END}"
    updated = pattern.sub(replacement, original)
    tex_path.write_text(updated, encoding="utf-8")


class PaperWritingStage(BaseStage):
    """Update LaTeX section files via the ``ml-paper-writing`` skill CLI."""

    @property
    def name(self) -> str:
        return "paper_writing"

    def _should_skip(self, config: ConfigLoader, cache: CacheManager) -> bool:
        results_summary = (
            config.resolve_path("outputs_dir") / "model_tuning" / "results_summary.json"
        )
        figures_dir = config.resolve_path("figures_dir")
        input_paths = list(figures_dir.glob("*.pdf")) + [results_summary]
        return cache.check_inputs(self.name, input_paths)

    def _run(self, config: ConfigLoader) -> StageResult:
        start = time.monotonic()
        skill_cmd = config.get("skills.ml_paper_writing", "ml-paper-writing")
        sections_dir = config.resolve_path("sections_dir")
        results_summary = (
            config.resolve_path("outputs_dir") / "model_tuning" / "results_summary.json"
        )
        figures_dir = config.resolve_path("figures_dir")
        outputs_dir = config.resolve_path("outputs_dir") / "paper_writing"
        outputs_dir.mkdir(parents=True, exist_ok=True)

        cmd = [
            skill_cmd,
            "--sections-dir", str(sections_dir),
            "--results-json", str(results_summary),
            "--figures-dir", str(figures_dir),
            "--output-dir", str(outputs_dir),
        ]

        try:
            self.run_subprocess(cmd)
        except Exception as exc:  # noqa: BLE001
            return StageResult(
                stage=self.name,
                status=StageStatus.FAILED,
                elapsed_seconds=time.monotonic() - start,
                message=str(exc),
            )

        # Apply any auto-generated replacements produced by the skill.
        artifacts = []
        for generated in outputs_dir.glob("*.tex"):
            target = sections_dir / generated.name
            if target.exists():
                _replace_autogenerated_blocks(target, generated.read_text(encoding="utf-8"))
                artifacts.append(str(target))

        return StageResult(
            stage=self.name,
            status=StageStatus.COMPLETED,
            elapsed_seconds=time.monotonic() - start,
            artifacts=artifacts,
        )
